"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        board_s = {}
        board_t = {}
        for i in s:
            if i not in board_s:
                board_s[i] = 1
            else:
                board_s[i] += 1
        for i in t:
            if i not in board_t:
                board_t[i] = 1
            else:
                board_t[i] += 1
        for key in board_t:
            if key not in board_s or board_t[key] != board_s[key]:
                return key
